function SetupDispAngle(phandle)
% for updating 'ANGLE PANEL'
% default phandle should be one of:   
%   TP.PI.UI.H0.hAxesAngle
%   TP.UI.H0.hAxesAngle                                

global TP

    %% Prepare Parameters
    if ~isfield(TP.D.Mky,'Side')
        TP.D.Mky.Side = 'right';
        % if not recorded, default is 'right' side
    end;
    if ~isfield(TP.D.Mky,'AngleXY')
        TP.D.Mky.AngleXY = 90;
    end;
    
    ColorTrans =    [.5 .5 .5];
    ColorScan =     [0  .5  0];
    
    if strcmpi(TP.D.Mky.Side, 'right')
        TP.D.Mky.AngleXYdisp = 45 + TP.D.Mky.AngleXY;
    elseif strcmpi(TP.D.Mky.Side, 'left')
        TP.D.Mky.AngleXYdisp = 45 - TP.D.Mky.AngleXY;
    else
        errordlg('Which side do you mean?');
    end;

    %% Prepare UI

    la = 1;
    sa = 0.95;
    set(phandle, 'NextPlot', 'replace');

    plot(   [-sa+0.15 la], [0 0], 'parent', phandle,...
            'Color', ColorTrans, 'LineWidth',2);
   
    set(phandle, 'color', [0 0 0]);        
    set(phandle, 'NextPlot', 'add');
    
    plot(   [0 0], [-sa+0.15 la], 'parent', phandle,...
            'Color', ColorTrans, 'LineWidth',2);

    plot(   [0 cos(TP.D.Mky.AngleXYdisp /180*pi)],...
            [0 sin(TP.D.Mky.AngleXYdisp /180*pi)],...
            'parent', phandle,...            
            'Color', ColorScan, 'LineWidth',2);

    plot(   [0 cos( (TP.D.Mky.AngleXYdisp-90) /180*pi)],...
            [0 sin( (TP.D.Mky.AngleXYdisp-90) /180*pi)],...
            'parent', phandle,...
            'Color', ColorScan, 'LineWidth',2);

    % 'image angle'
    text(   0,0,...
            {'image','angle'},...
            'parent', phandle,...
            'FontSize', 10,...
            'HorizontalAlignment', 'Center',...
            'VerticalAlignment', 'Middle',...
            'BackgroundColor', ColorScan,...
            'Margin', 15,...
            'Rotation', TP.D.Mky.AngleXYdisp);

    % Y (scan)
    text(   cos(TP.D.Mky.AngleXYdisp /180*pi),...
            sin(TP.D.Mky.AngleXYdisp /180*pi),...
            'Y (scan)',...
            'parent', phandle,...
            'FontSize', 10,...
            'HorizontalAlignment', 'Right',...
            'VerticalAlignment', 'Bottom',...
            'Color', ColorScan,...
            'Rotation', TP.D.Mky.AngleXYdisp);

    % X (scan)
    text(   cos( (TP.D.Mky.AngleXYdisp-90) /180*pi),...
            sin( (TP.D.Mky.AngleXYdisp-90) /180*pi),...
            'X (scan)',...
            'parent', phandle,...
            'FontSize', 10,...
            'HorizontalAlignment', 'Right',...
            'VerticalAlignment', 'Bottom',...
            'Color', ColorScan,...
            'Rotation', TP.D.Mky.AngleXYdisp-90);
    
    % X (translation)   
    text(   0, -la,...
            '\leftarrow X (translation) \rightarrow',...
            'parent', phandle,...
            'FontSize', 10,...
            'HorizontalAlignment', 'Center',...
            'VerticalAlignment', 'Bottom',...
            'Color', ColorTrans);
        
     % Y (translation)   
    text(   -la, 0,...
            '\leftarrow Y (translation) \rightarrow',...
            'parent', phandle,...
            'FontSize', 10,...
            'HorizontalAlignment', 'Center',...
            'VerticalAlignment', 'Top',...
            'Color', ColorTrans,...
            'Rotation',90);
 
	set(phandle, 'Ylim', [-1 1], 'Xlim', [-1 1]);
